# NumPy's functions

In [2]:
import numpy as np

## arange

Methods start with a <code>.</code> after <code>np</code>. In the following example, <code>arange</code> gives you an array from 0 to 7 but not including 7.

In [3]:
np.arange(0, 7)

array([0, 1, 2, 3, 4, 5, 6])

Here is another example:

In [4]:
np.arange(10, 23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

NumPy includes the start value and excludes the stop value. Here is an example:

In [5]:
np.arange(10, 26, 5)

array([10, 15, 20, 25])

## linspace

[<code>linspace</code>](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) create a group of integeres that are linearly or integrally spaced.

In [6]:
np.linspace(5, 15, 9)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

## zeros

In [7]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((5,3,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])