# Slicing

In [1]:
import numpy as np

Create a NumPy array

In [2]:
my_vector = np.array([3, 65, -6, 857, -36])
my_vector

array([  3,  65,  -6, 857, -36])

### Select an element in the array

In [3]:
my_vector[-2]

857

In [4]:
my_vector[305 % my_vector.size]

3

### Assign a value to an element

In [5]:
my_vector[0] = -9
my_vector

array([ -9,  65,  -6, 857, -36])

## Two Dimensional Arrays

Create a two deminsional array with 7 rows and 5 columns.

Notice the brackets at the beginning and the end.

In [6]:
rows = 7
columns = 5
my_array = np.arange(0, rows * columns)
my_array.shape = (rows, columns)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [7]:
my_array[-1]

array([30, 31, 32, 33, 34])

In [8]:
my_array[5][2]

27

## Three Dimensional Arrays

In [9]:
rows = 3
columns = 6
depth = 4
my_3d_array = np.arange(depth * rows * columns)
my_3d_array.shape = (depth, rows, columns)
my_3d_array

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53]],

       [[54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]]])

In [10]:
my_3d_array[1]

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [11]:
my_3d_array[1, 2]

array([30, 31, 32, 33, 34, 35])

In [12]:
my_3d_array[1, 2, 4]

34

In [13]:
my_3d_array[1, 2] = 555
my_3d_array

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17]],

       [[ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29],
        [555, 555, 555, 555, 555, 555]],

       [[ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53]],

       [[ 54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71]]])