# Boolean Mask Arrays

We are going to use two methods to acheive the same objectives:<br>
The first one uses the python logical operators and the second one uses <code>numpy.logical_and</code> function

Here, we want to create an array, see which elements are divisable by 7, then choose the ones that are greater than zero and put them in a new array.

## Python logical operators

In [1]:
import numpy as np

In [2]:
my_vector = np.array([-50, 6, 2, 67, -301, 14, 21])
my_vector

array([ -50,    6,    2,   67, -301,   14,   21])

Let's see which one is divisable by 7

In [3]:
zero_mod_7_mask = 0 == (my_vector % 7)
zero_mod_7_mask

array([False, False, False, False,  True,  True,  True])

Put them in a new array

In [4]:
sub_array = my_vector[zero_mod_7_mask]
sub_array

array([-301,   14,   21])

What are the elements are greater than 0?

In [5]:
sub_array[sub_array > 0]

array([14, 21])

## NumPy logical operators

In [6]:
mod_test = 0 == (my_vector % 7)

In [7]:
positive_test = my_vector > 0

In [8]:
combined_mask = np.logical_and(mod_test, positive_test)

In [9]:
my_vector[combined_mask]

array([14, 21])

<strong>When dealing with large arrays, using the NumPy logical operators is more efficient.</strong>