# Broadcasting

Broadcasting describes how NumPy performs operations between arrays with different sizes.

In [1]:
import numpy as np

In [2]:
rows, columns, depth = 5, 7, 2

my_3D_array = np.arange(depth * rows * columns)
my_3D_array.shape = (depth, rows, columns)
my_3D_array

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69]]])

In [3]:
# shape

my_3D_array.shape

(2, 5, 7)

In [4]:
# number of dimensions

my_3D_array.ndim

3

In [5]:
# number of elements within the array

my_3D_array.size

70

In [6]:
# data type for each element

my_3D_array.dtype

dtype('int64')

In [7]:
# arrithmatics

5 * my_3D_array - 2

array([[[ -2,   3,   8,  13,  18,  23,  28],
        [ 33,  38,  43,  48,  53,  58,  63],
        [ 68,  73,  78,  83,  88,  93,  98],
        [103, 108, 113, 118, 123, 128, 133],
        [138, 143, 148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193, 198, 203],
        [208, 213, 218, 223, 228, 233, 238],
        [243, 248, 253, 258, 263, 268, 273],
        [278, 283, 288, 293, 298, 303, 308],
        [313, 318, 323, 328, 333, 338, 343]]])

### Products of two matrices

For matrice multipication, use <code>np.dot</code>.

In [8]:
# create two matrices

left_mat = np.arange(0, 8).reshape(2, 4)
right_mat = np.arange(0, 12).reshape(4, 3)

In [9]:
np.dot(left_mat, right_mat)

array([[ 42,  48,  54],
       [114, 136, 158]])

### Operations along axes

In [10]:
my_3D_array

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69]]])

In [11]:
my_3D_array.sum()

2415

In [12]:

my_3D_array.sum(axis = 0) # columns (first dimension)


array([[ 35,  37,  39,  41,  43,  45,  47],
       [ 49,  51,  53,  55,  57,  59,  61],
       [ 63,  65,  67,  69,  71,  73,  75],
       [ 77,  79,  81,  83,  85,  87,  89],
       [ 91,  93,  95,  97,  99, 101, 103]])

In [13]:

my_3D_array.sum(axis = 1) #  rows (second dimension)


array([[ 70,  75,  80,  85,  90,  95, 100],
       [245, 250, 255, 260, 265, 270, 275]])

In [14]:

my_3D_array.sum(axis = 2)


array([[ 21,  70, 119, 168, 217],
       [266, 315, 364, 413, 462]])

## Broadcasting Rules

In [15]:
# create a 2 dimensional array

rows, columns = 7, 5

my_2D_array = np.ones(35, dtype = 'int_').reshape(rows, columns) * 3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])